// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BBandsSeries.proto

package io.hbar.protobuf.schema;

public final class BBandsSeriesSchema {
  private BBandsSeriesSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BBandsSeriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BBandsSeries)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .BBandsSeries.BBands series = 1;</code>
     */
    java.util.List<io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands> 
        getSeriesList();
    /**
     * <code>repeated .BBandsSeries.BBands series = 1;</code>
     */
    io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands getSeries(int index);
    /**
     * <code>repeated .BBandsSeries.BBands series = 1;</code>
     */
    int getSeriesCount();
    /**
     * <code>repeated .BBandsSeries.BBands series = 1;</code>
     */
    java.util.List<? extends io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBandsOrBuilder> 
        getSeriesOrBuilderList();
    /**
     * <code>repeated .BBandsSeries.BBands series = 1;</code>
     */
    io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBandsOrBuilder getSeriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code BBandsSeries}
   */
  public  static final class BBandsSeries extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BBandsSeries)
      BBandsSeriesOrBuilder {
    // Use BBandsSeries.newBuilder() to construct.
    private BBandsSeries(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private BBandsSeries() {
      series_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BBandsSeries(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                series_ = new java.util.ArrayList<io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands>();
                mutable_bitField0_ |= 0x00000001;
              }
              series_.add(input.readMessage(io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = java.util.Collections.unmodifiableList(series_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hbar.protobuf.schema.BBandsSeriesSchema.internal_static_BBandsSeries_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hbar.protobuf.schema.BBandsSeriesSchema.internal_static_BBandsSeries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.class, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.Builder.class);
    }

    public static final com.google.protobuf.Parser<BBandsSeries> PARSER =
        new com.google.protobuf.AbstractParser<BBandsSeries>() {
      public BBandsSeries parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BBandsSeries(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BBandsSeries> getParserForType() {
      return PARSER;
    }

    public interface BBandsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:BBandsSeries.BBands)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 timestamp = 1;</code>
       */
      boolean hasTimestamp();
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      int getTimestamp();

      /**
       * <code>required double upper = 2;</code>
       */
      boolean hasUpper();
      /**
       * <code>required double upper = 2;</code>
       */
      double getUpper();

      /**
       * <code>required double middle = 3;</code>
       */
      boolean hasMiddle();
      /**
       * <code>required double middle = 3;</code>
       */
      double getMiddle();

      /**
       * <code>required double lower = 4;</code>
       */
      boolean hasLower();
      /**
       * <code>required double lower = 4;</code>
       */
      double getLower();
    }
    /**
     * Protobuf type {@code BBandsSeries.BBands}
     */
    public  static final class BBands extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:BBandsSeries.BBands)
        BBandsOrBuilder {
      // Use BBands.newBuilder() to construct.
      private BBands(com.google.protobuf.GeneratedMessage.Builder builder) {
        super(builder);
      }
      private BBands() {
        timestamp_ = 0;
        upper_ = 0D;
        middle_ = 0D;
        lower_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private BBands(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                timestamp_ = input.readInt32();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                upper_ = input.readDouble();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                middle_ = input.readDouble();
                break;
              }
              case 33: {
                bitField0_ |= 0x00000008;
                lower_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.BBandsSeriesSchema.internal_static_BBandsSeries_BBands_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.BBandsSeriesSchema.internal_static_BBandsSeries_BBands_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.class, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder.class);
      }

      public static final com.google.protobuf.Parser<BBands> PARSER =
          new com.google.protobuf.AbstractParser<BBands>() {
        public BBands parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new BBands(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<BBands> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TIMESTAMP_FIELD_NUMBER = 1;
      private int timestamp_;
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }

      public static final int UPPER_FIELD_NUMBER = 2;
      private double upper_;
      /**
       * <code>required double upper = 2;</code>
       */
      public boolean hasUpper() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double upper = 2;</code>
       */
      public double getUpper() {
        return upper_;
      }

      public static final int MIDDLE_FIELD_NUMBER = 3;
      private double middle_;
      /**
       * <code>required double middle = 3;</code>
       */
      public boolean hasMiddle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double middle = 3;</code>
       */
      public double getMiddle() {
        return middle_;
      }

      public static final int LOWER_FIELD_NUMBER = 4;
      private double lower_;
      /**
       * <code>required double lower = 4;</code>
       */
      public boolean hasLower() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double lower = 4;</code>
       */
      public double getLower() {
        return lower_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasTimestamp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUpper()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasMiddle()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLower()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, upper_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeDouble(3, middle_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeDouble(4, lower_);
        }
        unknownFields.writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, upper_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, middle_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, lower_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return defaultInstance.toBuilder();
      }
      public static Builder newBuilder(io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands prototype) {
        return defaultInstance.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == defaultInstance
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code BBandsSeries.BBands}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:BBandsSeries.BBands)
          io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBandsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.hbar.protobuf.schema.BBandsSeriesSchema.internal_static_BBandsSeries_BBands_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.hbar.protobuf.schema.BBandsSeriesSchema.internal_static_BBandsSeries_BBands_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.class, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder.class);
        }

        // Construct using io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          timestamp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          upper_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          middle_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          lower_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.hbar.protobuf.schema.BBandsSeriesSchema.internal_static_BBandsSeries_BBands_descriptor;
        }

        public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands getDefaultInstanceForType() {
          return io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.getDefaultInstance();
        }

        public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands build() {
          io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands buildPartial() {
          io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands result = new io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.timestamp_ = timestamp_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.upper_ = upper_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.middle_ = middle_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.lower_ = lower_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands) {
            return mergeFrom((io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands other) {
          if (other == io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.getDefaultInstance()) return this;
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          if (other.hasUpper()) {
            setUpper(other.getUpper());
          }
          if (other.hasMiddle()) {
            setMiddle(other.getMiddle());
          }
          if (other.hasLower()) {
            setLower(other.getLower());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasTimestamp()) {
            
            return false;
          }
          if (!hasUpper()) {
            
            return false;
          }
          if (!hasMiddle()) {
            
            return false;
          }
          if (!hasLower()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int timestamp_ ;
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public int getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder setTimestamp(int value) {
          bitField0_ |= 0x00000001;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000001);
          timestamp_ = 0;
          onChanged();
          return this;
        }

        private double upper_ ;
        /**
         * <code>required double upper = 2;</code>
         */
        public boolean hasUpper() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double upper = 2;</code>
         */
        public double getUpper() {
          return upper_;
        }
        /**
         * <code>required double upper = 2;</code>
         */
        public Builder setUpper(double value) {
          bitField0_ |= 0x00000002;
          upper_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double upper = 2;</code>
         */
        public Builder clearUpper() {
          bitField0_ = (bitField0_ & ~0x00000002);
          upper_ = 0D;
          onChanged();
          return this;
        }

        private double middle_ ;
        /**
         * <code>required double middle = 3;</code>
         */
        public boolean hasMiddle() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required double middle = 3;</code>
         */
        public double getMiddle() {
          return middle_;
        }
        /**
         * <code>required double middle = 3;</code>
         */
        public Builder setMiddle(double value) {
          bitField0_ |= 0x00000004;
          middle_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double middle = 3;</code>
         */
        public Builder clearMiddle() {
          bitField0_ = (bitField0_ & ~0x00000004);
          middle_ = 0D;
          onChanged();
          return this;
        }

        private double lower_ ;
        /**
         * <code>required double lower = 4;</code>
         */
        public boolean hasLower() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required double lower = 4;</code>
         */
        public double getLower() {
          return lower_;
        }
        /**
         * <code>required double lower = 4;</code>
         */
        public Builder setLower(double value) {
          bitField0_ |= 0x00000008;
          lower_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double lower = 4;</code>
         */
        public Builder clearLower() {
          bitField0_ = (bitField0_ & ~0x00000008);
          lower_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:BBandsSeries.BBands)
      }

      // @@protoc_insertion_point(class_scope:BBandsSeries.BBands)
      private static final io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands defaultInstance;
      static {
        defaultInstance = new io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands();
      }

      public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands getDefaultInstance() {
        return defaultInstance;
      }

      public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands getDefaultInstanceForType() {
        return defaultInstance;
      }

      static {
      }
    }

    public static final int SERIES_FIELD_NUMBER = 1;
    private java.util.List<io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands> series_;
    /**
     * <code>repeated .BBandsSeries.BBands series = 1;</code>
     */
    public java.util.List<io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands> getSeriesList() {
      return series_;
    }
    /**
     * <code>repeated .BBandsSeries.BBands series = 1;</code>
     */
    public java.util.List<? extends io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBandsOrBuilder> 
        getSeriesOrBuilderList() {
      return series_;
    }
    /**
     * <code>repeated .BBandsSeries.BBands series = 1;</code>
     */
    public int getSeriesCount() {
      return series_.size();
    }
    /**
     * <code>repeated .BBandsSeries.BBands series = 1;</code>
     */
    public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands getSeries(int index) {
      return series_.get(index);
    }
    /**
     * <code>repeated .BBandsSeries.BBands series = 1;</code>
     */
    public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBandsOrBuilder getSeriesOrBuilder(
        int index) {
      return series_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSeriesCount(); i++) {
        if (!getSeries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < series_.size(); i++) {
        output.writeMessage(1, series_.get(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < series_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, series_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return defaultInstance.toBuilder();
    }
    public static Builder newBuilder(io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries prototype) {
      return defaultInstance.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == defaultInstance
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BBandsSeries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BBandsSeries)
        io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeriesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.BBandsSeriesSchema.internal_static_BBandsSeries_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.BBandsSeriesSchema.internal_static_BBandsSeries_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.class, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.Builder.class);
      }

      // Construct using io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSeriesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hbar.protobuf.schema.BBandsSeriesSchema.internal_static_BBandsSeries_descriptor;
      }

      public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries getDefaultInstanceForType() {
        return io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.getDefaultInstance();
      }

      public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries build() {
        io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries buildPartial() {
        io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries result = new io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries(this);
        int from_bitField0_ = bitField0_;
        if (seriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            series_ = java.util.Collections.unmodifiableList(series_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.series_ = series_;
        } else {
          result.series_ = seriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries) {
          return mergeFrom((io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries other) {
        if (other == io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.getDefaultInstance()) return this;
        if (seriesBuilder_ == null) {
          if (!other.series_.isEmpty()) {
            if (series_.isEmpty()) {
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSeriesIsMutable();
              series_.addAll(other.series_);
            }
            onChanged();
          }
        } else {
          if (!other.series_.isEmpty()) {
            if (seriesBuilder_.isEmpty()) {
              seriesBuilder_.dispose();
              seriesBuilder_ = null;
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
              seriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSeriesFieldBuilder() : null;
            } else {
              seriesBuilder_.addAllMessages(other.series_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSeriesCount(); i++) {
          if (!getSeries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands> series_ =
        java.util.Collections.emptyList();
      private void ensureSeriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = new java.util.ArrayList<io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands>(series_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBandsOrBuilder> seriesBuilder_;

      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands> getSeriesList() {
        if (seriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(series_);
        } else {
          return seriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public int getSeriesCount() {
        if (seriesBuilder_ == null) {
          return series_.size();
        } else {
          return seriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands getSeries(int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);
        } else {
          return seriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.set(index, value);
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.set(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public Builder addSeries(io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(index, value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public Builder addSeries(
          io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public Builder addAllSeries(
          java.lang.Iterable<? extends io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands> values) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, series_);
          onChanged();
        } else {
          seriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public Builder clearSeries() {
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public Builder removeSeries(int index) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.remove(index);
          onChanged();
        } else {
          seriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder getSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBandsOrBuilder getSeriesOrBuilder(
          int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);  } else {
          return seriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public java.util.List<? extends io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBandsOrBuilder> 
           getSeriesOrBuilderList() {
        if (seriesBuilder_ != null) {
          return seriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(series_);
        }
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder addSeriesBuilder() {
        return getSeriesFieldBuilder().addBuilder(
            io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.getDefaultInstance());
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder addSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().addBuilder(
            index, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.getDefaultInstance());
      }
      /**
       * <code>repeated .BBandsSeries.BBands series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder> 
           getSeriesBuilderList() {
        return getSeriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBandsOrBuilder> 
          getSeriesFieldBuilder() {
        if (seriesBuilder_ == null) {
          seriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBands.Builder, io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries.BBandsOrBuilder>(
                  series_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          series_ = null;
        }
        return seriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:BBandsSeries)
    }

    // @@protoc_insertion_point(class_scope:BBandsSeries)
    private static final io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries defaultInstance;
    static {
      defaultInstance = new io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries();
    }

    public static io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries getDefaultInstance() {
      return defaultInstance;
    }

    public io.hbar.protobuf.schema.BBandsSeriesSchema.BBandsSeries getDefaultInstanceForType() {
      return defaultInstance;
    }

    static {
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BBandsSeries_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BBandsSeries_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BBandsSeries_BBands_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BBandsSeries_BBands_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022BBandsSeries.proto\"\177\n\014BBandsSeries\022$\n\006" +
      "series\030\001 \003(\0132\024.BBandsSeries.BBands\032I\n\006BB" +
      "ands\022\021\n\ttimestamp\030\001 \002(\005\022\r\n\005upper\030\002 \002(\001\022\016" +
      "\n\006middle\030\003 \002(\001\022\r\n\005lower\030\004 \002(\001B-\n\027io.hbar" +
      ".protobuf.schemaB\022BBandsSeriesSchema"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BBandsSeries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BBandsSeries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BBandsSeries_descriptor,
        new java.lang.String[] { "Series", });
    internal_static_BBandsSeries_BBands_descriptor =
      internal_static_BBandsSeries_descriptor.getNestedTypes().get(0);
    internal_static_BBandsSeries_BBands_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BBandsSeries_BBands_descriptor,
        new java.lang.String[] { "Timestamp", "Upper", "Middle", "Lower", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
