// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EMASeries.proto

package io.hbar.protobuf.schema;

public final class EMASeriesSchema {
  private EMASeriesSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EMASeriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EMASeries)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .EMASeries.EMA series = 1;</code>
     */
    java.util.List<io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA> 
        getSeriesList();
    /**
     * <code>repeated .EMASeries.EMA series = 1;</code>
     */
    io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA getSeries(int index);
    /**
     * <code>repeated .EMASeries.EMA series = 1;</code>
     */
    int getSeriesCount();
    /**
     * <code>repeated .EMASeries.EMA series = 1;</code>
     */
    java.util.List<? extends io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMAOrBuilder> 
        getSeriesOrBuilderList();
    /**
     * <code>repeated .EMASeries.EMA series = 1;</code>
     */
    io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMAOrBuilder getSeriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code EMASeries}
   */
  public  static final class EMASeries extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EMASeries)
      EMASeriesOrBuilder {
    // Use EMASeries.newBuilder() to construct.
    private EMASeries(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private EMASeries() {
      series_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EMASeries(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                series_ = new java.util.ArrayList<io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA>();
                mutable_bitField0_ |= 0x00000001;
              }
              series_.add(input.readMessage(io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = java.util.Collections.unmodifiableList(series_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hbar.protobuf.schema.EMASeriesSchema.internal_static_EMASeries_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hbar.protobuf.schema.EMASeriesSchema.internal_static_EMASeries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.class, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.Builder.class);
    }

    public static final com.google.protobuf.Parser<EMASeries> PARSER =
        new com.google.protobuf.AbstractParser<EMASeries>() {
      public EMASeries parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new EMASeries(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EMASeries> getParserForType() {
      return PARSER;
    }

    public interface EMAOrBuilder extends
        // @@protoc_insertion_point(interface_extends:EMASeries.EMA)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 timestamp = 1;</code>
       */
      boolean hasTimestamp();
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      int getTimestamp();

      /**
       * <code>required double value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required double value = 2;</code>
       */
      double getValue();
    }
    /**
     * Protobuf type {@code EMASeries.EMA}
     */
    public  static final class EMA extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:EMASeries.EMA)
        EMAOrBuilder {
      // Use EMA.newBuilder() to construct.
      private EMA(com.google.protobuf.GeneratedMessage.Builder builder) {
        super(builder);
      }
      private EMA() {
        timestamp_ = 0;
        value_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private EMA(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                timestamp_ = input.readInt32();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                value_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.EMASeriesSchema.internal_static_EMASeries_EMA_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.EMASeriesSchema.internal_static_EMASeries_EMA_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.class, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder.class);
      }

      public static final com.google.protobuf.Parser<EMA> PARSER =
          new com.google.protobuf.AbstractParser<EMA>() {
        public EMA parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new EMA(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<EMA> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TIMESTAMP_FIELD_NUMBER = 1;
      private int timestamp_;
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private double value_;
      /**
       * <code>required double value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasTimestamp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, value_);
        }
        unknownFields.writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, value_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return defaultInstance.toBuilder();
      }
      public static Builder newBuilder(io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA prototype) {
        return defaultInstance.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == defaultInstance
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code EMASeries.EMA}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:EMASeries.EMA)
          io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMAOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.hbar.protobuf.schema.EMASeriesSchema.internal_static_EMASeries_EMA_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.hbar.protobuf.schema.EMASeriesSchema.internal_static_EMASeries_EMA_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.class, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder.class);
        }

        // Construct using io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          timestamp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.hbar.protobuf.schema.EMASeriesSchema.internal_static_EMASeries_EMA_descriptor;
        }

        public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA getDefaultInstanceForType() {
          return io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.getDefaultInstance();
        }

        public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA build() {
          io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA buildPartial() {
          io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA result = new io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.timestamp_ = timestamp_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA) {
            return mergeFrom((io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA other) {
          if (other == io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.getDefaultInstance()) return this;
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasTimestamp()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int timestamp_ ;
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public int getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder setTimestamp(int value) {
          bitField0_ |= 0x00000001;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000001);
          timestamp_ = 0;
          onChanged();
          return this;
        }

        private double value_ ;
        /**
         * <code>required double value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double value = 2;</code>
         */
        public double getValue() {
          return value_;
        }
        /**
         * <code>required double value = 2;</code>
         */
        public Builder setValue(double value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:EMASeries.EMA)
      }

      // @@protoc_insertion_point(class_scope:EMASeries.EMA)
      private static final io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA defaultInstance;
      static {
        defaultInstance = new io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA();
      }

      public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA getDefaultInstance() {
        return defaultInstance;
      }

      public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA getDefaultInstanceForType() {
        return defaultInstance;
      }

      static {
      }
    }

    public static final int SERIES_FIELD_NUMBER = 1;
    private java.util.List<io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA> series_;
    /**
     * <code>repeated .EMASeries.EMA series = 1;</code>
     */
    public java.util.List<io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA> getSeriesList() {
      return series_;
    }
    /**
     * <code>repeated .EMASeries.EMA series = 1;</code>
     */
    public java.util.List<? extends io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMAOrBuilder> 
        getSeriesOrBuilderList() {
      return series_;
    }
    /**
     * <code>repeated .EMASeries.EMA series = 1;</code>
     */
    public int getSeriesCount() {
      return series_.size();
    }
    /**
     * <code>repeated .EMASeries.EMA series = 1;</code>
     */
    public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA getSeries(int index) {
      return series_.get(index);
    }
    /**
     * <code>repeated .EMASeries.EMA series = 1;</code>
     */
    public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMAOrBuilder getSeriesOrBuilder(
        int index) {
      return series_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSeriesCount(); i++) {
        if (!getSeries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < series_.size(); i++) {
        output.writeMessage(1, series_.get(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < series_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, series_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return defaultInstance.toBuilder();
    }
    public static Builder newBuilder(io.hbar.protobuf.schema.EMASeriesSchema.EMASeries prototype) {
      return defaultInstance.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == defaultInstance
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EMASeries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EMASeries)
        io.hbar.protobuf.schema.EMASeriesSchema.EMASeriesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.EMASeriesSchema.internal_static_EMASeries_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.EMASeriesSchema.internal_static_EMASeries_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.class, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.Builder.class);
      }

      // Construct using io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSeriesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hbar.protobuf.schema.EMASeriesSchema.internal_static_EMASeries_descriptor;
      }

      public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries getDefaultInstanceForType() {
        return io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.getDefaultInstance();
      }

      public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries build() {
        io.hbar.protobuf.schema.EMASeriesSchema.EMASeries result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries buildPartial() {
        io.hbar.protobuf.schema.EMASeriesSchema.EMASeries result = new io.hbar.protobuf.schema.EMASeriesSchema.EMASeries(this);
        int from_bitField0_ = bitField0_;
        if (seriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            series_ = java.util.Collections.unmodifiableList(series_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.series_ = series_;
        } else {
          result.series_ = seriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hbar.protobuf.schema.EMASeriesSchema.EMASeries) {
          return mergeFrom((io.hbar.protobuf.schema.EMASeriesSchema.EMASeries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hbar.protobuf.schema.EMASeriesSchema.EMASeries other) {
        if (other == io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.getDefaultInstance()) return this;
        if (seriesBuilder_ == null) {
          if (!other.series_.isEmpty()) {
            if (series_.isEmpty()) {
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSeriesIsMutable();
              series_.addAll(other.series_);
            }
            onChanged();
          }
        } else {
          if (!other.series_.isEmpty()) {
            if (seriesBuilder_.isEmpty()) {
              seriesBuilder_.dispose();
              seriesBuilder_ = null;
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
              seriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSeriesFieldBuilder() : null;
            } else {
              seriesBuilder_.addAllMessages(other.series_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSeriesCount(); i++) {
          if (!getSeries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hbar.protobuf.schema.EMASeriesSchema.EMASeries parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hbar.protobuf.schema.EMASeriesSchema.EMASeries) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA> series_ =
        java.util.Collections.emptyList();
      private void ensureSeriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = new java.util.ArrayList<io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA>(series_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMAOrBuilder> seriesBuilder_;

      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA> getSeriesList() {
        if (seriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(series_);
        } else {
          return seriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public int getSeriesCount() {
        if (seriesBuilder_ == null) {
          return series_.size();
        } else {
          return seriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA getSeries(int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);
        } else {
          return seriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.set(index, value);
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.set(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public Builder addSeries(io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(index, value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public Builder addSeries(
          io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public Builder addAllSeries(
          java.lang.Iterable<? extends io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA> values) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, series_);
          onChanged();
        } else {
          seriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public Builder clearSeries() {
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public Builder removeSeries(int index) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.remove(index);
          onChanged();
        } else {
          seriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder getSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMAOrBuilder getSeriesOrBuilder(
          int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);  } else {
          return seriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public java.util.List<? extends io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMAOrBuilder> 
           getSeriesOrBuilderList() {
        if (seriesBuilder_ != null) {
          return seriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(series_);
        }
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder addSeriesBuilder() {
        return getSeriesFieldBuilder().addBuilder(
            io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.getDefaultInstance());
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder addSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().addBuilder(
            index, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.getDefaultInstance());
      }
      /**
       * <code>repeated .EMASeries.EMA series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder> 
           getSeriesBuilderList() {
        return getSeriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMAOrBuilder> 
          getSeriesFieldBuilder() {
        if (seriesBuilder_ == null) {
          seriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMA.Builder, io.hbar.protobuf.schema.EMASeriesSchema.EMASeries.EMAOrBuilder>(
                  series_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          series_ = null;
        }
        return seriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:EMASeries)
    }

    // @@protoc_insertion_point(class_scope:EMASeries)
    private static final io.hbar.protobuf.schema.EMASeriesSchema.EMASeries defaultInstance;
    static {
      defaultInstance = new io.hbar.protobuf.schema.EMASeriesSchema.EMASeries();
    }

    public static io.hbar.protobuf.schema.EMASeriesSchema.EMASeries getDefaultInstance() {
      return defaultInstance;
    }

    public io.hbar.protobuf.schema.EMASeriesSchema.EMASeries getDefaultInstanceForType() {
      return defaultInstance;
    }

    static {
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EMASeries_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EMASeries_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EMASeries_EMA_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EMASeries_EMA_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017EMASeries.proto\"T\n\tEMASeries\022\036\n\006series" +
      "\030\001 \003(\0132\016.EMASeries.EMA\032\'\n\003EMA\022\021\n\ttimesta" +
      "mp\030\001 \002(\005\022\r\n\005value\030\002 \002(\001B*\n\027io.hbar.proto" +
      "buf.schemaB\017EMASeriesSchema"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EMASeries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EMASeries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EMASeries_descriptor,
        new java.lang.String[] { "Series", });
    internal_static_EMASeries_EMA_descriptor =
      internal_static_EMASeries_descriptor.getNestedTypes().get(0);
    internal_static_EMASeries_EMA_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EMASeries_EMA_descriptor,
        new java.lang.String[] { "Timestamp", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
