// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LinearRegSeries.proto

package io.hbar.protobuf.schema;

public final class LinearRegSeriesSchema {
  private LinearRegSeriesSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LinearRegSeriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LinearRegSeries)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
     */
    java.util.List<io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg> 
        getSeriesList();
    /**
     * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
     */
    io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg getSeries(int index);
    /**
     * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
     */
    int getSeriesCount();
    /**
     * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
     */
    java.util.List<? extends io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearRegOrBuilder> 
        getSeriesOrBuilderList();
    /**
     * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
     */
    io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearRegOrBuilder getSeriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code LinearRegSeries}
   */
  public  static final class LinearRegSeries extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LinearRegSeries)
      LinearRegSeriesOrBuilder {
    // Use LinearRegSeries.newBuilder() to construct.
    private LinearRegSeries(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private LinearRegSeries() {
      series_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LinearRegSeries(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                series_ = new java.util.ArrayList<io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg>();
                mutable_bitField0_ |= 0x00000001;
              }
              series_.add(input.readMessage(io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = java.util.Collections.unmodifiableList(series_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hbar.protobuf.schema.LinearRegSeriesSchema.internal_static_LinearRegSeries_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hbar.protobuf.schema.LinearRegSeriesSchema.internal_static_LinearRegSeries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.class, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.Builder.class);
    }

    public static final com.google.protobuf.Parser<LinearRegSeries> PARSER =
        new com.google.protobuf.AbstractParser<LinearRegSeries>() {
      public LinearRegSeries parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new LinearRegSeries(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LinearRegSeries> getParserForType() {
      return PARSER;
    }

    public interface LinearRegOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LinearRegSeries.LinearReg)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 timestamp = 1;</code>
       */
      boolean hasTimestamp();
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      int getTimestamp();

      /**
       * <code>required double value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required double value = 2;</code>
       */
      double getValue();
    }
    /**
     * Protobuf type {@code LinearRegSeries.LinearReg}
     */
    public  static final class LinearReg extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:LinearRegSeries.LinearReg)
        LinearRegOrBuilder {
      // Use LinearReg.newBuilder() to construct.
      private LinearReg(com.google.protobuf.GeneratedMessage.Builder builder) {
        super(builder);
      }
      private LinearReg() {
        timestamp_ = 0;
        value_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private LinearReg(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                timestamp_ = input.readInt32();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                value_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.LinearRegSeriesSchema.internal_static_LinearRegSeries_LinearReg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.LinearRegSeriesSchema.internal_static_LinearRegSeries_LinearReg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.class, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder.class);
      }

      public static final com.google.protobuf.Parser<LinearReg> PARSER =
          new com.google.protobuf.AbstractParser<LinearReg>() {
        public LinearReg parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new LinearReg(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<LinearReg> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TIMESTAMP_FIELD_NUMBER = 1;
      private int timestamp_;
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private double value_;
      /**
       * <code>required double value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasTimestamp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, value_);
        }
        unknownFields.writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, value_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return defaultInstance.toBuilder();
      }
      public static Builder newBuilder(io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg prototype) {
        return defaultInstance.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == defaultInstance
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code LinearRegSeries.LinearReg}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:LinearRegSeries.LinearReg)
          io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearRegOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.hbar.protobuf.schema.LinearRegSeriesSchema.internal_static_LinearRegSeries_LinearReg_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.hbar.protobuf.schema.LinearRegSeriesSchema.internal_static_LinearRegSeries_LinearReg_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.class, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder.class);
        }

        // Construct using io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          timestamp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.hbar.protobuf.schema.LinearRegSeriesSchema.internal_static_LinearRegSeries_LinearReg_descriptor;
        }

        public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg getDefaultInstanceForType() {
          return io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.getDefaultInstance();
        }

        public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg build() {
          io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg buildPartial() {
          io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg result = new io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.timestamp_ = timestamp_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg) {
            return mergeFrom((io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg other) {
          if (other == io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.getDefaultInstance()) return this;
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasTimestamp()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int timestamp_ ;
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public int getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder setTimestamp(int value) {
          bitField0_ |= 0x00000001;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000001);
          timestamp_ = 0;
          onChanged();
          return this;
        }

        private double value_ ;
        /**
         * <code>required double value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double value = 2;</code>
         */
        public double getValue() {
          return value_;
        }
        /**
         * <code>required double value = 2;</code>
         */
        public Builder setValue(double value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:LinearRegSeries.LinearReg)
      }

      // @@protoc_insertion_point(class_scope:LinearRegSeries.LinearReg)
      private static final io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg defaultInstance;
      static {
        defaultInstance = new io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg();
      }

      public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg getDefaultInstance() {
        return defaultInstance;
      }

      public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg getDefaultInstanceForType() {
        return defaultInstance;
      }

      static {
      }
    }

    public static final int SERIES_FIELD_NUMBER = 1;
    private java.util.List<io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg> series_;
    /**
     * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
     */
    public java.util.List<io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg> getSeriesList() {
      return series_;
    }
    /**
     * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
     */
    public java.util.List<? extends io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearRegOrBuilder> 
        getSeriesOrBuilderList() {
      return series_;
    }
    /**
     * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
     */
    public int getSeriesCount() {
      return series_.size();
    }
    /**
     * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
     */
    public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg getSeries(int index) {
      return series_.get(index);
    }
    /**
     * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
     */
    public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearRegOrBuilder getSeriesOrBuilder(
        int index) {
      return series_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSeriesCount(); i++) {
        if (!getSeries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < series_.size(); i++) {
        output.writeMessage(1, series_.get(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < series_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, series_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return defaultInstance.toBuilder();
    }
    public static Builder newBuilder(io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries prototype) {
      return defaultInstance.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == defaultInstance
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LinearRegSeries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LinearRegSeries)
        io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeriesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.LinearRegSeriesSchema.internal_static_LinearRegSeries_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.LinearRegSeriesSchema.internal_static_LinearRegSeries_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.class, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.Builder.class);
      }

      // Construct using io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSeriesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hbar.protobuf.schema.LinearRegSeriesSchema.internal_static_LinearRegSeries_descriptor;
      }

      public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries getDefaultInstanceForType() {
        return io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.getDefaultInstance();
      }

      public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries build() {
        io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries buildPartial() {
        io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries result = new io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries(this);
        int from_bitField0_ = bitField0_;
        if (seriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            series_ = java.util.Collections.unmodifiableList(series_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.series_ = series_;
        } else {
          result.series_ = seriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries) {
          return mergeFrom((io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries other) {
        if (other == io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.getDefaultInstance()) return this;
        if (seriesBuilder_ == null) {
          if (!other.series_.isEmpty()) {
            if (series_.isEmpty()) {
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSeriesIsMutable();
              series_.addAll(other.series_);
            }
            onChanged();
          }
        } else {
          if (!other.series_.isEmpty()) {
            if (seriesBuilder_.isEmpty()) {
              seriesBuilder_.dispose();
              seriesBuilder_ = null;
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
              seriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSeriesFieldBuilder() : null;
            } else {
              seriesBuilder_.addAllMessages(other.series_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSeriesCount(); i++) {
          if (!getSeries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg> series_ =
        java.util.Collections.emptyList();
      private void ensureSeriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = new java.util.ArrayList<io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg>(series_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearRegOrBuilder> seriesBuilder_;

      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg> getSeriesList() {
        if (seriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(series_);
        } else {
          return seriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public int getSeriesCount() {
        if (seriesBuilder_ == null) {
          return series_.size();
        } else {
          return seriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg getSeries(int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);
        } else {
          return seriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.set(index, value);
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.set(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public Builder addSeries(io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(index, value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public Builder addSeries(
          io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public Builder addAllSeries(
          java.lang.Iterable<? extends io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg> values) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, series_);
          onChanged();
        } else {
          seriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public Builder clearSeries() {
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public Builder removeSeries(int index) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.remove(index);
          onChanged();
        } else {
          seriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder getSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearRegOrBuilder getSeriesOrBuilder(
          int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);  } else {
          return seriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public java.util.List<? extends io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearRegOrBuilder> 
           getSeriesOrBuilderList() {
        if (seriesBuilder_ != null) {
          return seriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(series_);
        }
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder addSeriesBuilder() {
        return getSeriesFieldBuilder().addBuilder(
            io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.getDefaultInstance());
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder addSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().addBuilder(
            index, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.getDefaultInstance());
      }
      /**
       * <code>repeated .LinearRegSeries.LinearReg series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder> 
           getSeriesBuilderList() {
        return getSeriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearRegOrBuilder> 
          getSeriesFieldBuilder() {
        if (seriesBuilder_ == null) {
          seriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearReg.Builder, io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries.LinearRegOrBuilder>(
                  series_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          series_ = null;
        }
        return seriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:LinearRegSeries)
    }

    // @@protoc_insertion_point(class_scope:LinearRegSeries)
    private static final io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries defaultInstance;
    static {
      defaultInstance = new io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries();
    }

    public static io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries getDefaultInstance() {
      return defaultInstance;
    }

    public io.hbar.protobuf.schema.LinearRegSeriesSchema.LinearRegSeries getDefaultInstanceForType() {
      return defaultInstance;
    }

    static {
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LinearRegSeries_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LinearRegSeries_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LinearRegSeries_LinearReg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LinearRegSeries_LinearReg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025LinearRegSeries.proto\"l\n\017LinearRegSeri" +
      "es\022*\n\006series\030\001 \003(\0132\032.LinearRegSeries.Lin" +
      "earReg\032-\n\tLinearReg\022\021\n\ttimestamp\030\001 \002(\005\022\r" +
      "\n\005value\030\002 \002(\001B0\n\027io.hbar.protobuf.schema" +
      "B\025LinearRegSeriesSchema"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LinearRegSeries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LinearRegSeries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LinearRegSeries_descriptor,
        new java.lang.String[] { "Series", });
    internal_static_LinearRegSeries_LinearReg_descriptor =
      internal_static_LinearRegSeries_descriptor.getNestedTypes().get(0);
    internal_static_LinearRegSeries_LinearReg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LinearRegSeries_LinearReg_descriptor,
        new java.lang.String[] { "Timestamp", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
