// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MACDSeries.proto

package io.hbar.protobuf.schema;

public final class MACDSeriesSchema {
  private MACDSeriesSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MACDSeriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MACDSeries)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MACDSeries.MACD series = 1;</code>
     */
    java.util.List<io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD> 
        getSeriesList();
    /**
     * <code>repeated .MACDSeries.MACD series = 1;</code>
     */
    io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD getSeries(int index);
    /**
     * <code>repeated .MACDSeries.MACD series = 1;</code>
     */
    int getSeriesCount();
    /**
     * <code>repeated .MACDSeries.MACD series = 1;</code>
     */
    java.util.List<? extends io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACDOrBuilder> 
        getSeriesOrBuilderList();
    /**
     * <code>repeated .MACDSeries.MACD series = 1;</code>
     */
    io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACDOrBuilder getSeriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MACDSeries}
   */
  public  static final class MACDSeries extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MACDSeries)
      MACDSeriesOrBuilder {
    // Use MACDSeries.newBuilder() to construct.
    private MACDSeries(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private MACDSeries() {
      series_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MACDSeries(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                series_ = new java.util.ArrayList<io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD>();
                mutable_bitField0_ |= 0x00000001;
              }
              series_.add(input.readMessage(io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = java.util.Collections.unmodifiableList(series_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hbar.protobuf.schema.MACDSeriesSchema.internal_static_MACDSeries_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hbar.protobuf.schema.MACDSeriesSchema.internal_static_MACDSeries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.class, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.Builder.class);
    }

    public static final com.google.protobuf.Parser<MACDSeries> PARSER =
        new com.google.protobuf.AbstractParser<MACDSeries>() {
      public MACDSeries parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MACDSeries(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MACDSeries> getParserForType() {
      return PARSER;
    }

    public interface MACDOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MACDSeries.MACD)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 timestamp = 1;</code>
       */
      boolean hasTimestamp();
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      int getTimestamp();

      /**
       * <code>required double macd = 2;</code>
       */
      boolean hasMacd();
      /**
       * <code>required double macd = 2;</code>
       */
      double getMacd();

      /**
       * <code>required double signal = 3;</code>
       */
      boolean hasSignal();
      /**
       * <code>required double signal = 3;</code>
       */
      double getSignal();

      /**
       * <code>required double histogram = 4;</code>
       */
      boolean hasHistogram();
      /**
       * <code>required double histogram = 4;</code>
       */
      double getHistogram();
    }
    /**
     * Protobuf type {@code MACDSeries.MACD}
     */
    public  static final class MACD extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:MACDSeries.MACD)
        MACDOrBuilder {
      // Use MACD.newBuilder() to construct.
      private MACD(com.google.protobuf.GeneratedMessage.Builder builder) {
        super(builder);
      }
      private MACD() {
        timestamp_ = 0;
        macd_ = 0D;
        signal_ = 0D;
        histogram_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private MACD(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                timestamp_ = input.readInt32();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                macd_ = input.readDouble();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                signal_ = input.readDouble();
                break;
              }
              case 33: {
                bitField0_ |= 0x00000008;
                histogram_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.MACDSeriesSchema.internal_static_MACDSeries_MACD_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.MACDSeriesSchema.internal_static_MACDSeries_MACD_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.class, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder.class);
      }

      public static final com.google.protobuf.Parser<MACD> PARSER =
          new com.google.protobuf.AbstractParser<MACD>() {
        public MACD parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new MACD(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MACD> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TIMESTAMP_FIELD_NUMBER = 1;
      private int timestamp_;
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }

      public static final int MACD_FIELD_NUMBER = 2;
      private double macd_;
      /**
       * <code>required double macd = 2;</code>
       */
      public boolean hasMacd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double macd = 2;</code>
       */
      public double getMacd() {
        return macd_;
      }

      public static final int SIGNAL_FIELD_NUMBER = 3;
      private double signal_;
      /**
       * <code>required double signal = 3;</code>
       */
      public boolean hasSignal() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double signal = 3;</code>
       */
      public double getSignal() {
        return signal_;
      }

      public static final int HISTOGRAM_FIELD_NUMBER = 4;
      private double histogram_;
      /**
       * <code>required double histogram = 4;</code>
       */
      public boolean hasHistogram() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double histogram = 4;</code>
       */
      public double getHistogram() {
        return histogram_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasTimestamp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasMacd()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSignal()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasHistogram()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, macd_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeDouble(3, signal_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeDouble(4, histogram_);
        }
        unknownFields.writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, macd_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, signal_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, histogram_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return defaultInstance.toBuilder();
      }
      public static Builder newBuilder(io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD prototype) {
        return defaultInstance.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == defaultInstance
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code MACDSeries.MACD}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:MACDSeries.MACD)
          io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACDOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.hbar.protobuf.schema.MACDSeriesSchema.internal_static_MACDSeries_MACD_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.hbar.protobuf.schema.MACDSeriesSchema.internal_static_MACDSeries_MACD_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.class, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder.class);
        }

        // Construct using io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          timestamp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          macd_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          signal_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          histogram_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.hbar.protobuf.schema.MACDSeriesSchema.internal_static_MACDSeries_MACD_descriptor;
        }

        public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD getDefaultInstanceForType() {
          return io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.getDefaultInstance();
        }

        public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD build() {
          io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD buildPartial() {
          io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD result = new io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.timestamp_ = timestamp_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.macd_ = macd_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.signal_ = signal_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.histogram_ = histogram_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD) {
            return mergeFrom((io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD other) {
          if (other == io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.getDefaultInstance()) return this;
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          if (other.hasMacd()) {
            setMacd(other.getMacd());
          }
          if (other.hasSignal()) {
            setSignal(other.getSignal());
          }
          if (other.hasHistogram()) {
            setHistogram(other.getHistogram());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasTimestamp()) {
            
            return false;
          }
          if (!hasMacd()) {
            
            return false;
          }
          if (!hasSignal()) {
            
            return false;
          }
          if (!hasHistogram()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int timestamp_ ;
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public int getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder setTimestamp(int value) {
          bitField0_ |= 0x00000001;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000001);
          timestamp_ = 0;
          onChanged();
          return this;
        }

        private double macd_ ;
        /**
         * <code>required double macd = 2;</code>
         */
        public boolean hasMacd() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double macd = 2;</code>
         */
        public double getMacd() {
          return macd_;
        }
        /**
         * <code>required double macd = 2;</code>
         */
        public Builder setMacd(double value) {
          bitField0_ |= 0x00000002;
          macd_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double macd = 2;</code>
         */
        public Builder clearMacd() {
          bitField0_ = (bitField0_ & ~0x00000002);
          macd_ = 0D;
          onChanged();
          return this;
        }

        private double signal_ ;
        /**
         * <code>required double signal = 3;</code>
         */
        public boolean hasSignal() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required double signal = 3;</code>
         */
        public double getSignal() {
          return signal_;
        }
        /**
         * <code>required double signal = 3;</code>
         */
        public Builder setSignal(double value) {
          bitField0_ |= 0x00000004;
          signal_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double signal = 3;</code>
         */
        public Builder clearSignal() {
          bitField0_ = (bitField0_ & ~0x00000004);
          signal_ = 0D;
          onChanged();
          return this;
        }

        private double histogram_ ;
        /**
         * <code>required double histogram = 4;</code>
         */
        public boolean hasHistogram() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required double histogram = 4;</code>
         */
        public double getHistogram() {
          return histogram_;
        }
        /**
         * <code>required double histogram = 4;</code>
         */
        public Builder setHistogram(double value) {
          bitField0_ |= 0x00000008;
          histogram_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double histogram = 4;</code>
         */
        public Builder clearHistogram() {
          bitField0_ = (bitField0_ & ~0x00000008);
          histogram_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:MACDSeries.MACD)
      }

      // @@protoc_insertion_point(class_scope:MACDSeries.MACD)
      private static final io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD defaultInstance;
      static {
        defaultInstance = new io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD();
      }

      public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD getDefaultInstance() {
        return defaultInstance;
      }

      public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD getDefaultInstanceForType() {
        return defaultInstance;
      }

      static {
      }
    }

    public static final int SERIES_FIELD_NUMBER = 1;
    private java.util.List<io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD> series_;
    /**
     * <code>repeated .MACDSeries.MACD series = 1;</code>
     */
    public java.util.List<io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD> getSeriesList() {
      return series_;
    }
    /**
     * <code>repeated .MACDSeries.MACD series = 1;</code>
     */
    public java.util.List<? extends io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACDOrBuilder> 
        getSeriesOrBuilderList() {
      return series_;
    }
    /**
     * <code>repeated .MACDSeries.MACD series = 1;</code>
     */
    public int getSeriesCount() {
      return series_.size();
    }
    /**
     * <code>repeated .MACDSeries.MACD series = 1;</code>
     */
    public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD getSeries(int index) {
      return series_.get(index);
    }
    /**
     * <code>repeated .MACDSeries.MACD series = 1;</code>
     */
    public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACDOrBuilder getSeriesOrBuilder(
        int index) {
      return series_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSeriesCount(); i++) {
        if (!getSeries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < series_.size(); i++) {
        output.writeMessage(1, series_.get(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < series_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, series_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return defaultInstance.toBuilder();
    }
    public static Builder newBuilder(io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries prototype) {
      return defaultInstance.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == defaultInstance
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MACDSeries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MACDSeries)
        io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeriesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.MACDSeriesSchema.internal_static_MACDSeries_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.MACDSeriesSchema.internal_static_MACDSeries_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.class, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.Builder.class);
      }

      // Construct using io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSeriesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hbar.protobuf.schema.MACDSeriesSchema.internal_static_MACDSeries_descriptor;
      }

      public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries getDefaultInstanceForType() {
        return io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.getDefaultInstance();
      }

      public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries build() {
        io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries buildPartial() {
        io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries result = new io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries(this);
        int from_bitField0_ = bitField0_;
        if (seriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            series_ = java.util.Collections.unmodifiableList(series_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.series_ = series_;
        } else {
          result.series_ = seriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries) {
          return mergeFrom((io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries other) {
        if (other == io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.getDefaultInstance()) return this;
        if (seriesBuilder_ == null) {
          if (!other.series_.isEmpty()) {
            if (series_.isEmpty()) {
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSeriesIsMutable();
              series_.addAll(other.series_);
            }
            onChanged();
          }
        } else {
          if (!other.series_.isEmpty()) {
            if (seriesBuilder_.isEmpty()) {
              seriesBuilder_.dispose();
              seriesBuilder_ = null;
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
              seriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSeriesFieldBuilder() : null;
            } else {
              seriesBuilder_.addAllMessages(other.series_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSeriesCount(); i++) {
          if (!getSeries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD> series_ =
        java.util.Collections.emptyList();
      private void ensureSeriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = new java.util.ArrayList<io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD>(series_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACDOrBuilder> seriesBuilder_;

      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD> getSeriesList() {
        if (seriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(series_);
        } else {
          return seriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public int getSeriesCount() {
        if (seriesBuilder_ == null) {
          return series_.size();
        } else {
          return seriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD getSeries(int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);
        } else {
          return seriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.set(index, value);
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.set(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public Builder addSeries(io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(index, value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public Builder addSeries(
          io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public Builder addAllSeries(
          java.lang.Iterable<? extends io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD> values) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, series_);
          onChanged();
        } else {
          seriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public Builder clearSeries() {
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public Builder removeSeries(int index) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.remove(index);
          onChanged();
        } else {
          seriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder getSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACDOrBuilder getSeriesOrBuilder(
          int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);  } else {
          return seriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public java.util.List<? extends io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACDOrBuilder> 
           getSeriesOrBuilderList() {
        if (seriesBuilder_ != null) {
          return seriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(series_);
        }
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder addSeriesBuilder() {
        return getSeriesFieldBuilder().addBuilder(
            io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.getDefaultInstance());
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder addSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().addBuilder(
            index, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.getDefaultInstance());
      }
      /**
       * <code>repeated .MACDSeries.MACD series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder> 
           getSeriesBuilderList() {
        return getSeriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACDOrBuilder> 
          getSeriesFieldBuilder() {
        if (seriesBuilder_ == null) {
          seriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACD.Builder, io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries.MACDOrBuilder>(
                  series_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          series_ = null;
        }
        return seriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MACDSeries)
    }

    // @@protoc_insertion_point(class_scope:MACDSeries)
    private static final io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries defaultInstance;
    static {
      defaultInstance = new io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries();
    }

    public static io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries getDefaultInstance() {
      return defaultInstance;
    }

    public io.hbar.protobuf.schema.MACDSeriesSchema.MACDSeries getDefaultInstanceForType() {
      return defaultInstance;
    }

    static {
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MACDSeries_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MACDSeries_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MACDSeries_MACD_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MACDSeries_MACD_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MACDSeries.proto\"z\n\nMACDSeries\022 \n\006seri" +
      "es\030\001 \003(\0132\020.MACDSeries.MACD\032J\n\004MACD\022\021\n\tti" +
      "mestamp\030\001 \002(\005\022\014\n\004macd\030\002 \002(\001\022\016\n\006signal\030\003 " +
      "\002(\001\022\021\n\thistogram\030\004 \002(\001B+\n\027io.hbar.protob" +
      "uf.schemaB\020MACDSeriesSchema"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MACDSeries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MACDSeries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MACDSeries_descriptor,
        new java.lang.String[] { "Series", });
    internal_static_MACDSeries_MACD_descriptor =
      internal_static_MACDSeries_descriptor.getNestedTypes().get(0);
    internal_static_MACDSeries_MACD_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MACDSeries_MACD_descriptor,
        new java.lang.String[] { "Timestamp", "Macd", "Signal", "Histogram", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
