// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OHLCVSeries.proto

package io.hbar.protobuf.schema;

public final class OHLCVSeriesSchema {
  private OHLCVSeriesSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OHLCVSeriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OHLCVSeries)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
     */
    java.util.List<io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV> 
        getSeriesList();
    /**
     * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
     */
    io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV getSeries(int index);
    /**
     * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
     */
    int getSeriesCount();
    /**
     * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
     */
    java.util.List<? extends io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCVOrBuilder> 
        getSeriesOrBuilderList();
    /**
     * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
     */
    io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCVOrBuilder getSeriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code OHLCVSeries}
   */
  public  static final class OHLCVSeries extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:OHLCVSeries)
      OHLCVSeriesOrBuilder {
    // Use OHLCVSeries.newBuilder() to construct.
    private OHLCVSeries(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private OHLCVSeries() {
      series_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OHLCVSeries(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                series_ = new java.util.ArrayList<io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV>();
                mutable_bitField0_ |= 0x00000001;
              }
              series_.add(input.readMessage(io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = java.util.Collections.unmodifiableList(series_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hbar.protobuf.schema.OHLCVSeriesSchema.internal_static_OHLCVSeries_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hbar.protobuf.schema.OHLCVSeriesSchema.internal_static_OHLCVSeries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.class, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.Builder.class);
    }

    public static final com.google.protobuf.Parser<OHLCVSeries> PARSER =
        new com.google.protobuf.AbstractParser<OHLCVSeries>() {
      public OHLCVSeries parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new OHLCVSeries(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OHLCVSeries> getParserForType() {
      return PARSER;
    }

    public interface OHLCVOrBuilder extends
        // @@protoc_insertion_point(interface_extends:OHLCVSeries.OHLCV)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 timestamp = 1;</code>
       */
      boolean hasTimestamp();
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      int getTimestamp();

      /**
       * <code>required double open = 2;</code>
       */
      boolean hasOpen();
      /**
       * <code>required double open = 2;</code>
       */
      double getOpen();

      /**
       * <code>required double high = 3;</code>
       */
      boolean hasHigh();
      /**
       * <code>required double high = 3;</code>
       */
      double getHigh();

      /**
       * <code>required double low = 4;</code>
       */
      boolean hasLow();
      /**
       * <code>required double low = 4;</code>
       */
      double getLow();

      /**
       * <code>required double close = 5;</code>
       */
      boolean hasClose();
      /**
       * <code>required double close = 5;</code>
       */
      double getClose();

      /**
       * <code>required double volume = 6;</code>
       */
      boolean hasVolume();
      /**
       * <code>required double volume = 6;</code>
       */
      double getVolume();
    }
    /**
     * Protobuf type {@code OHLCVSeries.OHLCV}
     */
    public  static final class OHLCV extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:OHLCVSeries.OHLCV)
        OHLCVOrBuilder {
      // Use OHLCV.newBuilder() to construct.
      private OHLCV(com.google.protobuf.GeneratedMessage.Builder builder) {
        super(builder);
      }
      private OHLCV() {
        timestamp_ = 0;
        open_ = 0D;
        high_ = 0D;
        low_ = 0D;
        close_ = 0D;
        volume_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private OHLCV(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                timestamp_ = input.readInt32();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                open_ = input.readDouble();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                high_ = input.readDouble();
                break;
              }
              case 33: {
                bitField0_ |= 0x00000008;
                low_ = input.readDouble();
                break;
              }
              case 41: {
                bitField0_ |= 0x00000010;
                close_ = input.readDouble();
                break;
              }
              case 49: {
                bitField0_ |= 0x00000020;
                volume_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.OHLCVSeriesSchema.internal_static_OHLCVSeries_OHLCV_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.OHLCVSeriesSchema.internal_static_OHLCVSeries_OHLCV_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.class, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder.class);
      }

      public static final com.google.protobuf.Parser<OHLCV> PARSER =
          new com.google.protobuf.AbstractParser<OHLCV>() {
        public OHLCV parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new OHLCV(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<OHLCV> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TIMESTAMP_FIELD_NUMBER = 1;
      private int timestamp_;
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }

      public static final int OPEN_FIELD_NUMBER = 2;
      private double open_;
      /**
       * <code>required double open = 2;</code>
       */
      public boolean hasOpen() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double open = 2;</code>
       */
      public double getOpen() {
        return open_;
      }

      public static final int HIGH_FIELD_NUMBER = 3;
      private double high_;
      /**
       * <code>required double high = 3;</code>
       */
      public boolean hasHigh() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double high = 3;</code>
       */
      public double getHigh() {
        return high_;
      }

      public static final int LOW_FIELD_NUMBER = 4;
      private double low_;
      /**
       * <code>required double low = 4;</code>
       */
      public boolean hasLow() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double low = 4;</code>
       */
      public double getLow() {
        return low_;
      }

      public static final int CLOSE_FIELD_NUMBER = 5;
      private double close_;
      /**
       * <code>required double close = 5;</code>
       */
      public boolean hasClose() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required double close = 5;</code>
       */
      public double getClose() {
        return close_;
      }

      public static final int VOLUME_FIELD_NUMBER = 6;
      private double volume_;
      /**
       * <code>required double volume = 6;</code>
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required double volume = 6;</code>
       */
      public double getVolume() {
        return volume_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasTimestamp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasOpen()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasHigh()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLow()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasClose()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasVolume()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, open_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeDouble(3, high_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeDouble(4, low_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeDouble(5, close_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeDouble(6, volume_);
        }
        unknownFields.writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, open_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, high_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, low_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(5, close_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(6, volume_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return defaultInstance.toBuilder();
      }
      public static Builder newBuilder(io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV prototype) {
        return defaultInstance.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == defaultInstance
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code OHLCVSeries.OHLCV}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:OHLCVSeries.OHLCV)
          io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCVOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.hbar.protobuf.schema.OHLCVSeriesSchema.internal_static_OHLCVSeries_OHLCV_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.hbar.protobuf.schema.OHLCVSeriesSchema.internal_static_OHLCVSeries_OHLCV_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.class, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder.class);
        }

        // Construct using io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          timestamp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          open_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          high_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          low_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000008);
          close_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000010);
          volume_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.hbar.protobuf.schema.OHLCVSeriesSchema.internal_static_OHLCVSeries_OHLCV_descriptor;
        }

        public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV getDefaultInstanceForType() {
          return io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.getDefaultInstance();
        }

        public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV build() {
          io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV buildPartial() {
          io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV result = new io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.timestamp_ = timestamp_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.open_ = open_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.high_ = high_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.low_ = low_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.close_ = close_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.volume_ = volume_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV) {
            return mergeFrom((io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV other) {
          if (other == io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.getDefaultInstance()) return this;
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          if (other.hasOpen()) {
            setOpen(other.getOpen());
          }
          if (other.hasHigh()) {
            setHigh(other.getHigh());
          }
          if (other.hasLow()) {
            setLow(other.getLow());
          }
          if (other.hasClose()) {
            setClose(other.getClose());
          }
          if (other.hasVolume()) {
            setVolume(other.getVolume());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasTimestamp()) {
            
            return false;
          }
          if (!hasOpen()) {
            
            return false;
          }
          if (!hasHigh()) {
            
            return false;
          }
          if (!hasLow()) {
            
            return false;
          }
          if (!hasClose()) {
            
            return false;
          }
          if (!hasVolume()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int timestamp_ ;
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public int getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder setTimestamp(int value) {
          bitField0_ |= 0x00000001;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000001);
          timestamp_ = 0;
          onChanged();
          return this;
        }

        private double open_ ;
        /**
         * <code>required double open = 2;</code>
         */
        public boolean hasOpen() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double open = 2;</code>
         */
        public double getOpen() {
          return open_;
        }
        /**
         * <code>required double open = 2;</code>
         */
        public Builder setOpen(double value) {
          bitField0_ |= 0x00000002;
          open_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double open = 2;</code>
         */
        public Builder clearOpen() {
          bitField0_ = (bitField0_ & ~0x00000002);
          open_ = 0D;
          onChanged();
          return this;
        }

        private double high_ ;
        /**
         * <code>required double high = 3;</code>
         */
        public boolean hasHigh() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required double high = 3;</code>
         */
        public double getHigh() {
          return high_;
        }
        /**
         * <code>required double high = 3;</code>
         */
        public Builder setHigh(double value) {
          bitField0_ |= 0x00000004;
          high_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double high = 3;</code>
         */
        public Builder clearHigh() {
          bitField0_ = (bitField0_ & ~0x00000004);
          high_ = 0D;
          onChanged();
          return this;
        }

        private double low_ ;
        /**
         * <code>required double low = 4;</code>
         */
        public boolean hasLow() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required double low = 4;</code>
         */
        public double getLow() {
          return low_;
        }
        /**
         * <code>required double low = 4;</code>
         */
        public Builder setLow(double value) {
          bitField0_ |= 0x00000008;
          low_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double low = 4;</code>
         */
        public Builder clearLow() {
          bitField0_ = (bitField0_ & ~0x00000008);
          low_ = 0D;
          onChanged();
          return this;
        }

        private double close_ ;
        /**
         * <code>required double close = 5;</code>
         */
        public boolean hasClose() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required double close = 5;</code>
         */
        public double getClose() {
          return close_;
        }
        /**
         * <code>required double close = 5;</code>
         */
        public Builder setClose(double value) {
          bitField0_ |= 0x00000010;
          close_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double close = 5;</code>
         */
        public Builder clearClose() {
          bitField0_ = (bitField0_ & ~0x00000010);
          close_ = 0D;
          onChanged();
          return this;
        }

        private double volume_ ;
        /**
         * <code>required double volume = 6;</code>
         */
        public boolean hasVolume() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>required double volume = 6;</code>
         */
        public double getVolume() {
          return volume_;
        }
        /**
         * <code>required double volume = 6;</code>
         */
        public Builder setVolume(double value) {
          bitField0_ |= 0x00000020;
          volume_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double volume = 6;</code>
         */
        public Builder clearVolume() {
          bitField0_ = (bitField0_ & ~0x00000020);
          volume_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:OHLCVSeries.OHLCV)
      }

      // @@protoc_insertion_point(class_scope:OHLCVSeries.OHLCV)
      private static final io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV defaultInstance;
      static {
        defaultInstance = new io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV();
      }

      public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV getDefaultInstance() {
        return defaultInstance;
      }

      public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV getDefaultInstanceForType() {
        return defaultInstance;
      }

      static {
      }
    }

    public static final int SERIES_FIELD_NUMBER = 1;
    private java.util.List<io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV> series_;
    /**
     * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
     */
    public java.util.List<io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV> getSeriesList() {
      return series_;
    }
    /**
     * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
     */
    public java.util.List<? extends io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCVOrBuilder> 
        getSeriesOrBuilderList() {
      return series_;
    }
    /**
     * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
     */
    public int getSeriesCount() {
      return series_.size();
    }
    /**
     * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
     */
    public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV getSeries(int index) {
      return series_.get(index);
    }
    /**
     * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
     */
    public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCVOrBuilder getSeriesOrBuilder(
        int index) {
      return series_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSeriesCount(); i++) {
        if (!getSeries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < series_.size(); i++) {
        output.writeMessage(1, series_.get(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < series_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, series_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return defaultInstance.toBuilder();
    }
    public static Builder newBuilder(io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries prototype) {
      return defaultInstance.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == defaultInstance
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OHLCVSeries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OHLCVSeries)
        io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeriesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.OHLCVSeriesSchema.internal_static_OHLCVSeries_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.OHLCVSeriesSchema.internal_static_OHLCVSeries_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.class, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.Builder.class);
      }

      // Construct using io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSeriesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hbar.protobuf.schema.OHLCVSeriesSchema.internal_static_OHLCVSeries_descriptor;
      }

      public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries getDefaultInstanceForType() {
        return io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.getDefaultInstance();
      }

      public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries build() {
        io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries buildPartial() {
        io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries result = new io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries(this);
        int from_bitField0_ = bitField0_;
        if (seriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            series_ = java.util.Collections.unmodifiableList(series_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.series_ = series_;
        } else {
          result.series_ = seriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries) {
          return mergeFrom((io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries other) {
        if (other == io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.getDefaultInstance()) return this;
        if (seriesBuilder_ == null) {
          if (!other.series_.isEmpty()) {
            if (series_.isEmpty()) {
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSeriesIsMutable();
              series_.addAll(other.series_);
            }
            onChanged();
          }
        } else {
          if (!other.series_.isEmpty()) {
            if (seriesBuilder_.isEmpty()) {
              seriesBuilder_.dispose();
              seriesBuilder_ = null;
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
              seriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSeriesFieldBuilder() : null;
            } else {
              seriesBuilder_.addAllMessages(other.series_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSeriesCount(); i++) {
          if (!getSeries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV> series_ =
        java.util.Collections.emptyList();
      private void ensureSeriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = new java.util.ArrayList<io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV>(series_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCVOrBuilder> seriesBuilder_;

      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV> getSeriesList() {
        if (seriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(series_);
        } else {
          return seriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public int getSeriesCount() {
        if (seriesBuilder_ == null) {
          return series_.size();
        } else {
          return seriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV getSeries(int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);
        } else {
          return seriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.set(index, value);
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.set(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public Builder addSeries(io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(index, value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public Builder addSeries(
          io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public Builder addAllSeries(
          java.lang.Iterable<? extends io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV> values) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, series_);
          onChanged();
        } else {
          seriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public Builder clearSeries() {
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public Builder removeSeries(int index) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.remove(index);
          onChanged();
        } else {
          seriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder getSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCVOrBuilder getSeriesOrBuilder(
          int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);  } else {
          return seriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public java.util.List<? extends io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCVOrBuilder> 
           getSeriesOrBuilderList() {
        if (seriesBuilder_ != null) {
          return seriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(series_);
        }
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder addSeriesBuilder() {
        return getSeriesFieldBuilder().addBuilder(
            io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.getDefaultInstance());
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder addSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().addBuilder(
            index, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.getDefaultInstance());
      }
      /**
       * <code>repeated .OHLCVSeries.OHLCV series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder> 
           getSeriesBuilderList() {
        return getSeriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCVOrBuilder> 
          getSeriesFieldBuilder() {
        if (seriesBuilder_ == null) {
          seriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCV.Builder, io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries.OHLCVOrBuilder>(
                  series_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          series_ = null;
        }
        return seriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:OHLCVSeries)
    }

    // @@protoc_insertion_point(class_scope:OHLCVSeries)
    private static final io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries defaultInstance;
    static {
      defaultInstance = new io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries();
    }

    public static io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries getDefaultInstance() {
      return defaultInstance;
    }

    public io.hbar.protobuf.schema.OHLCVSeriesSchema.OHLCVSeries getDefaultInstanceForType() {
      return defaultInstance;
    }

    static {
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OHLCVSeries_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OHLCVSeries_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OHLCVSeries_OHLCV_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OHLCVSeries_OHLCV_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021OHLCVSeries.proto\"\225\001\n\013OHLCVSeries\022\"\n\006s" +
      "eries\030\001 \003(\0132\022.OHLCVSeries.OHLCV\032b\n\005OHLCV" +
      "\022\021\n\ttimestamp\030\001 \002(\005\022\014\n\004open\030\002 \002(\001\022\014\n\004hig" +
      "h\030\003 \002(\001\022\013\n\003low\030\004 \002(\001\022\r\n\005close\030\005 \002(\001\022\016\n\006v" +
      "olume\030\006 \002(\001B,\n\027io.hbar.protobuf.schemaB\021" +
      "OHLCVSeriesSchema"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OHLCVSeries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OHLCVSeries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OHLCVSeries_descriptor,
        new java.lang.String[] { "Series", });
    internal_static_OHLCVSeries_OHLCV_descriptor =
      internal_static_OHLCVSeries_descriptor.getNestedTypes().get(0);
    internal_static_OHLCVSeries_OHLCV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OHLCVSeries_OHLCV_descriptor,
        new java.lang.String[] { "Timestamp", "Open", "High", "Low", "Close", "Volume", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
