// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderSeries.proto

package io.hbar.protobuf.schema;

public final class OrderSeriesSchema {
  private OrderSeriesSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OrderSeriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderSeries)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .OrderSeries.Order series = 1;</code>
     */
    java.util.List<io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order> 
        getSeriesList();
    /**
     * <code>repeated .OrderSeries.Order series = 1;</code>
     */
    io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order getSeries(int index);
    /**
     * <code>repeated .OrderSeries.Order series = 1;</code>
     */
    int getSeriesCount();
    /**
     * <code>repeated .OrderSeries.Order series = 1;</code>
     */
    java.util.List<? extends io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.OrderOrBuilder> 
        getSeriesOrBuilderList();
    /**
     * <code>repeated .OrderSeries.Order series = 1;</code>
     */
    io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.OrderOrBuilder getSeriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code OrderSeries}
   */
  public  static final class OrderSeries extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:OrderSeries)
      OrderSeriesOrBuilder {
    // Use OrderSeries.newBuilder() to construct.
    private OrderSeries(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private OrderSeries() {
      series_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderSeries(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                series_ = new java.util.ArrayList<io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order>();
                mutable_bitField0_ |= 0x00000001;
              }
              series_.add(input.readMessage(io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = java.util.Collections.unmodifiableList(series_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hbar.protobuf.schema.OrderSeriesSchema.internal_static_OrderSeries_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hbar.protobuf.schema.OrderSeriesSchema.internal_static_OrderSeries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.class, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Builder.class);
    }

    public static final com.google.protobuf.Parser<OrderSeries> PARSER =
        new com.google.protobuf.AbstractParser<OrderSeries>() {
      public OrderSeries parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new OrderSeries(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OrderSeries> getParserForType() {
      return PARSER;
    }

    public interface OrderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:OrderSeries.Order)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 timestamp = 1;</code>
       */
      boolean hasTimestamp();
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      int getTimestamp();

      /**
       * <code>required double price = 2;</code>
       */
      boolean hasPrice();
      /**
       * <code>required double price = 2;</code>
       */
      double getPrice();

      /**
       * <code>required double volume = 3;</code>
       */
      boolean hasVolume();
      /**
       * <code>required double volume = 3;</code>
       */
      double getVolume();
    }
    /**
     * Protobuf type {@code OrderSeries.Order}
     */
    public  static final class Order extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:OrderSeries.Order)
        OrderOrBuilder {
      // Use Order.newBuilder() to construct.
      private Order(com.google.protobuf.GeneratedMessage.Builder builder) {
        super(builder);
      }
      private Order() {
        timestamp_ = 0;
        price_ = 0D;
        volume_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Order(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                timestamp_ = input.readInt32();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                price_ = input.readDouble();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                volume_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.OrderSeriesSchema.internal_static_OrderSeries_Order_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.OrderSeriesSchema.internal_static_OrderSeries_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.class, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder.class);
      }

      public static final com.google.protobuf.Parser<Order> PARSER =
          new com.google.protobuf.AbstractParser<Order>() {
        public Order parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new Order(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Order> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TIMESTAMP_FIELD_NUMBER = 1;
      private int timestamp_;
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 timestamp = 1;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }

      public static final int PRICE_FIELD_NUMBER = 2;
      private double price_;
      /**
       * <code>required double price = 2;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double price = 2;</code>
       */
      public double getPrice() {
        return price_;
      }

      public static final int VOLUME_FIELD_NUMBER = 3;
      private double volume_;
      /**
       * <code>required double volume = 3;</code>
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double volume = 3;</code>
       */
      public double getVolume() {
        return volume_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasTimestamp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPrice()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasVolume()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, price_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeDouble(3, volume_);
        }
        unknownFields.writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, timestamp_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, price_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, volume_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return defaultInstance.toBuilder();
      }
      public static Builder newBuilder(io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order prototype) {
        return defaultInstance.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == defaultInstance
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code OrderSeries.Order}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:OrderSeries.Order)
          io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.OrderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.hbar.protobuf.schema.OrderSeriesSchema.internal_static_OrderSeries_Order_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.hbar.protobuf.schema.OrderSeriesSchema.internal_static_OrderSeries_Order_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.class, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder.class);
        }

        // Construct using io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          timestamp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          price_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          volume_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.hbar.protobuf.schema.OrderSeriesSchema.internal_static_OrderSeries_Order_descriptor;
        }

        public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order getDefaultInstanceForType() {
          return io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.getDefaultInstance();
        }

        public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order build() {
          io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order buildPartial() {
          io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order result = new io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.timestamp_ = timestamp_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.price_ = price_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.volume_ = volume_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order) {
            return mergeFrom((io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order other) {
          if (other == io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.getDefaultInstance()) return this;
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          if (other.hasPrice()) {
            setPrice(other.getPrice());
          }
          if (other.hasVolume()) {
            setVolume(other.getVolume());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasTimestamp()) {
            
            return false;
          }
          if (!hasPrice()) {
            
            return false;
          }
          if (!hasVolume()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int timestamp_ ;
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public int getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder setTimestamp(int value) {
          bitField0_ |= 0x00000001;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 timestamp = 1;</code>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000001);
          timestamp_ = 0;
          onChanged();
          return this;
        }

        private double price_ ;
        /**
         * <code>required double price = 2;</code>
         */
        public boolean hasPrice() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double price = 2;</code>
         */
        public double getPrice() {
          return price_;
        }
        /**
         * <code>required double price = 2;</code>
         */
        public Builder setPrice(double value) {
          bitField0_ |= 0x00000002;
          price_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double price = 2;</code>
         */
        public Builder clearPrice() {
          bitField0_ = (bitField0_ & ~0x00000002);
          price_ = 0D;
          onChanged();
          return this;
        }

        private double volume_ ;
        /**
         * <code>required double volume = 3;</code>
         */
        public boolean hasVolume() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required double volume = 3;</code>
         */
        public double getVolume() {
          return volume_;
        }
        /**
         * <code>required double volume = 3;</code>
         */
        public Builder setVolume(double value) {
          bitField0_ |= 0x00000004;
          volume_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double volume = 3;</code>
         */
        public Builder clearVolume() {
          bitField0_ = (bitField0_ & ~0x00000004);
          volume_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:OrderSeries.Order)
      }

      // @@protoc_insertion_point(class_scope:OrderSeries.Order)
      private static final io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order defaultInstance;
      static {
        defaultInstance = new io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order();
      }

      public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order getDefaultInstance() {
        return defaultInstance;
      }

      public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order getDefaultInstanceForType() {
        return defaultInstance;
      }

      static {
      }
    }

    public static final int SERIES_FIELD_NUMBER = 1;
    private java.util.List<io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order> series_;
    /**
     * <code>repeated .OrderSeries.Order series = 1;</code>
     */
    public java.util.List<io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order> getSeriesList() {
      return series_;
    }
    /**
     * <code>repeated .OrderSeries.Order series = 1;</code>
     */
    public java.util.List<? extends io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.OrderOrBuilder> 
        getSeriesOrBuilderList() {
      return series_;
    }
    /**
     * <code>repeated .OrderSeries.Order series = 1;</code>
     */
    public int getSeriesCount() {
      return series_.size();
    }
    /**
     * <code>repeated .OrderSeries.Order series = 1;</code>
     */
    public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order getSeries(int index) {
      return series_.get(index);
    }
    /**
     * <code>repeated .OrderSeries.Order series = 1;</code>
     */
    public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.OrderOrBuilder getSeriesOrBuilder(
        int index) {
      return series_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getSeriesCount(); i++) {
        if (!getSeries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < series_.size(); i++) {
        output.writeMessage(1, series_.get(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < series_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, series_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return defaultInstance.toBuilder();
    }
    public static Builder newBuilder(io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries prototype) {
      return defaultInstance.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == defaultInstance
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderSeries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderSeries)
        io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeriesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbar.protobuf.schema.OrderSeriesSchema.internal_static_OrderSeries_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbar.protobuf.schema.OrderSeriesSchema.internal_static_OrderSeries_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.class, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Builder.class);
      }

      // Construct using io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSeriesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hbar.protobuf.schema.OrderSeriesSchema.internal_static_OrderSeries_descriptor;
      }

      public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries getDefaultInstanceForType() {
        return io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.getDefaultInstance();
      }

      public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries build() {
        io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries buildPartial() {
        io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries result = new io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries(this);
        int from_bitField0_ = bitField0_;
        if (seriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            series_ = java.util.Collections.unmodifiableList(series_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.series_ = series_;
        } else {
          result.series_ = seriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries) {
          return mergeFrom((io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries other) {
        if (other == io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.getDefaultInstance()) return this;
        if (seriesBuilder_ == null) {
          if (!other.series_.isEmpty()) {
            if (series_.isEmpty()) {
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSeriesIsMutable();
              series_.addAll(other.series_);
            }
            onChanged();
          }
        } else {
          if (!other.series_.isEmpty()) {
            if (seriesBuilder_.isEmpty()) {
              seriesBuilder_.dispose();
              seriesBuilder_ = null;
              series_ = other.series_;
              bitField0_ = (bitField0_ & ~0x00000001);
              seriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSeriesFieldBuilder() : null;
            } else {
              seriesBuilder_.addAllMessages(other.series_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSeriesCount(); i++) {
          if (!getSeries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order> series_ =
        java.util.Collections.emptyList();
      private void ensureSeriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          series_ = new java.util.ArrayList<io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order>(series_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.OrderOrBuilder> seriesBuilder_;

      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order> getSeriesList() {
        if (seriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(series_);
        } else {
          return seriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public int getSeriesCount() {
        if (seriesBuilder_ == null) {
          return series_.size();
        } else {
          return seriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order getSeries(int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);
        } else {
          return seriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.set(index, value);
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public Builder setSeries(
          int index, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.set(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public Builder addSeries(io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order value) {
        if (seriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeriesIsMutable();
          series_.add(index, value);
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public Builder addSeries(
          io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public Builder addSeries(
          int index, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder builderForValue) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.add(index, builderForValue.build());
          onChanged();
        } else {
          seriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public Builder addAllSeries(
          java.lang.Iterable<? extends io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order> values) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, series_);
          onChanged();
        } else {
          seriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public Builder clearSeries() {
        if (seriesBuilder_ == null) {
          series_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          seriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public Builder removeSeries(int index) {
        if (seriesBuilder_ == null) {
          ensureSeriesIsMutable();
          series_.remove(index);
          onChanged();
        } else {
          seriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder getSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.OrderOrBuilder getSeriesOrBuilder(
          int index) {
        if (seriesBuilder_ == null) {
          return series_.get(index);  } else {
          return seriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public java.util.List<? extends io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.OrderOrBuilder> 
           getSeriesOrBuilderList() {
        if (seriesBuilder_ != null) {
          return seriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(series_);
        }
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder addSeriesBuilder() {
        return getSeriesFieldBuilder().addBuilder(
            io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder addSeriesBuilder(
          int index) {
        return getSeriesFieldBuilder().addBuilder(
            index, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.getDefaultInstance());
      }
      /**
       * <code>repeated .OrderSeries.Order series = 1;</code>
       */
      public java.util.List<io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder> 
           getSeriesBuilderList() {
        return getSeriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.OrderOrBuilder> 
          getSeriesFieldBuilder() {
        if (seriesBuilder_ == null) {
          seriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.Order.Builder, io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries.OrderOrBuilder>(
                  series_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          series_ = null;
        }
        return seriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:OrderSeries)
    }

    // @@protoc_insertion_point(class_scope:OrderSeries)
    private static final io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries defaultInstance;
    static {
      defaultInstance = new io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries();
    }

    public static io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries getDefaultInstance() {
      return defaultInstance;
    }

    public io.hbar.protobuf.schema.OrderSeriesSchema.OrderSeries getDefaultInstanceForType() {
      return defaultInstance;
    }

    static {
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderSeries_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderSeries_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderSeries_Order_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderSeries_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021OrderSeries.proto\"l\n\013OrderSeries\022\"\n\006se" +
      "ries\030\001 \003(\0132\022.OrderSeries.Order\0329\n\005Order\022" +
      "\021\n\ttimestamp\030\001 \002(\005\022\r\n\005price\030\002 \002(\001\022\016\n\006vol" +
      "ume\030\003 \002(\001B,\n\027io.hbar.protobuf.schemaB\021Or" +
      "derSeriesSchema"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OrderSeries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderSeries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OrderSeries_descriptor,
        new java.lang.String[] { "Series", });
    internal_static_OrderSeries_Order_descriptor =
      internal_static_OrderSeries_descriptor.getNestedTypes().get(0);
    internal_static_OrderSeries_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OrderSeries_Order_descriptor,
        new java.lang.String[] { "Timestamp", "Price", "Volume", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
